const catalogColumns = [
	{
		field: "name",
		label: "Название",
		isFirst: true,
		disablePadding: true,
		numeric: false,
		type: "string",
		minWidth: 170,
		numeric: false,
		isHeader: true,
		isTable: true,
		isSortable: true,
	},
	{
		field: "code",
		label: "Код",
		type: "string",
		numeric: false,
		minWidth: 100,
		isHeader: true,
		disablePadding: false,
		numeric: false,
		isTable: true,
		isSortable: true,
	},
	{
		field: "category",
		label: "Категория",
		numeric: false,
		type: "string",
		minWidth: 170,
		isHeader: true,
		isTable: true,
		numeric: false,
		disablePadding: false,
		isSortable: true,
	},
	{
		field: "price",
		label: "Цена",
		type: "number",
		minWidth: 170,
		numeric: true,
		isHeader: true,
		numeric: false,
		isTable: true,
		disablePadding: false,
		isSortable: true,
		format: (value) => Number(value),
	},
	{
		field: "actions",
		type: "children",
		minWidth: 170,
		isHeader: true,
		isTable: true,
		numeric: false,
		disablePadding: false,
	},
];

export default catalogColumns